def configure(shard):
    shard.properties.SpellWords = {
        'thel': 'AugmentWeapon',
        'mute': 'ConditionMuted',
        'cloak': 'ConditionCloaked',
        'loth': 'ConditionBlinded',
        'loz':  'ConditionFrozen',
        'roth': 'DamageOverTime',
        'reth': 'DamageSingleTarget',
        'aoh':  'ElementalAcid',
        'rei':  'ElementalDemonic',
        'feth': 'ElementalDivine',
        'rik':  'ElementalElectricity',
        'zel':  'ElementalFire',
        'zohl': 'ElementalIce',
        'mohr': 'ElementalForce',
        'mar':  'HealEffect',
        'muun': 'InflictCondition',
        'nohs': 'Sunder',
        'rage': 'ConditionEnraged',
    }
